// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGy_NZN2QHzc2oM5F24hfFGymvsWVvxlQ',
    appId: '1:481586799931:web:b13f1a8b713873ad40831e',
    messagingSenderId: '481586799931',
    projectId: 'smart-farming-app-kenya-2026',
    authDomain: 'smart-farming-app-kenya-2026.firebaseapp.com',
    storageBucket: 'smart-farming-app-kenya-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTKhJTmDOblYcVZ8BIBlZ7_f4mcX_kZhw',
    appId: '1:481586799931:android:3a227b82b80c72e740831e',
    messagingSenderId: '481586799931',
    projectId: 'smart-farming-app-kenya-2026',
    storageBucket: 'smart-farming-app-kenya-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYcC47FoAWQ6uY4YhGCDU5jPYbciI8P4',
    appId: '1:481586799931:ios:6f12ea07f24c442f40831e',
    messagingSenderId: '481586799931',
    projectId: 'smart-farming-app-kenya-2026',
    storageBucket: 'smart-farming-app-kenya-2026.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADYcC47FoAWQ6uY4YhGCDU5jPYbciI8P4',
    appId: '1:481586799931:ios:6f12ea07f24c442f40831e',
    messagingSenderId: '481586799931',
    projectId: 'smart-farming-app-kenya-2026',
    storageBucket: 'smart-farming-app-kenya-2026.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGy_NZN2QHzc2oM5F24hfFGymvsWVvxlQ',
    appId: '1:481586799931:web:06725d78f1e58ce040831e',
    messagingSenderId: '481586799931',
    projectId: 'smart-farming-app-kenya-2026',
    authDomain: 'smart-farming-app-kenya-2026.firebaseapp.com',
    storageBucket: 'smart-farming-app-kenya-2026.firebasestorage.app',
  );

}